baseURL     = 'https://www.jonleithe.no/'
locale      = 'en-gb'
theme       ='PaperMod'

[params]
defaultTheme    = "auto"
ShowReadingTime = true
hideFooter      = false

[params.profileMode]
enabled     = true
subtitle    = "Systems Engineer · Scientific Infrastructure · Software Development · Linux"
imageUrl    = "/images/2026-07-profile-sketch.png"
imageTitle  = "Jon Leithe"
imageWidth  = 250
imageHeight = 250



### Configure buttons ##########################################################
################################################################################



### Configuring the main menu ##################################################
#[[menu.main]]
#name = "Projects"
#url = "/projects/"
#weight = 20

#[[menu.main]]
#name = "CV"
#url = "/cv/"
#weight = 40
################################################################################
