project:
  type: website
  output-dir: build/site
  render:
    - index.md
    - "notes/personal/**/*.md"

format:
  html:
    format-links: false

website:
  page-navigation: true
  sidebar:
    style: docked
    search: true
